name: arway_flutter_demo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  #cupertino icons 
  cupertino_icons: ^1.0.2

  # unity integration
  flutter_unity_widget: ^2022.1.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
